### PR TITLE
[MIG] Migrate all modules to v11

### PR DESCRIPTION
**Pull request by CGenie**
This is an extension of #148 but I managed to migrate the web wizard and as far as I can tell everything works, even the reconfiguration of `sale.order.line` as noted in https://github.com/pledra/odoo-product-configurator/pull/148#issuecomment-396615929

### CODE REVIEW

**Comment by CGenie** [comment]
The last commit actually fixes the issue with that `sale.order.line` editing, I don't know why it was added in PR #148 .

**Comment by CasVissers-360ERP** [comment]
Thnx @CGenie closed my pr so we can continue here.

**Comment by ska-ibees** [comment]
Guys, Thanks for putting efforts for V11 migration!
During testing latest PR code, I am not able to use any custom field. 
If i do not set a field as custom, it works otherwise gives error.

@CGenie Could you please confirm if you have same issue?

(Please note:  sb.com is my local domain hosted in VM)

I am getting below error.
Error:
Uncaught TypeError: Cannot read property '1' of undefined

http://www.sb.com/web/static/src/js/views/basic/basic_model.js:3456
Traceback:
TypeError: Cannot read property '1' of undefined
    at http://www.sb.com/web/static/src/js/views/basic/basic_model.js:3456:46
    at Function._.each._.forEach (http://www.sb.com/web/static/lib/underscore/underscore.js:145:9)
    at Class._parseServerData (http://www.sb.com/web/static/src/js/views/basic/basic_model.js:3442:11)
    at Object.<anonymous> (http://www.sb.com/web/static/src/js/views/basic/basic_model.js:2005:22)
    at Object.<anonymous> (http://www.sb.com/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://www.sb.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://www.sb.com/web/static/lib/jquery/jquery.js:3231:49)
    at Object.<anonymous> (http://www.sb.com/web/static/lib/jquery/jquery.js:3283:104)
    at fire (http://www.sb.com/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://www.sb.com/web/static/lib/jquery/jquery.js:3231:49)

**Comment by CGenie** [comment]
@CasVissers thank you for reporting that, I think I found the solution.

**Comment by ska-ibees** [comment]
@CGenie Thanks for the fix. 
However, found more issues as listed below:
1. Can not complete Product configuration wizard if ONLY custom field is used and there is no Configuration STEP created in product template. However, if Step is configured then it works. Is it mandatory to have at-least one step?

2. 'Back' button on Product wizard modal is not working. Getting below error:

Error:
Uncaught TypeError: Cannot read property 'always' of undefined

http://www.sb.com/web/content/1035-16ff838/web.assets_backend.js:1414
Traceback:
### **### TypeError: Cannot read property 'always' of undefined**
    at Class._onButtonClicked (http://www.sb.com/web/content/1035-16ff838/web.assets_backend.js:1414:5)
    at Class.<anonymous> (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:3923:11)
    at Class.trigger (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:3921:180)
    at Class._trigger_up (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:3927:365)
    at Class._trigger_up (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:3927:449)
    at Class.trigger_up (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:3927:280)
    at HTMLButtonElement.<anonymous> (http://www.sb.com/web/content/1035-16ff838/web.assets_backend.js:1372:334)
    at HTMLButtonElement.dispatch (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:892:451)
    at HTMLButtonElement.elemData.handle (http://www.sb.com/web/content/874-da88ef7/web.assets_common.js:865:173)

4. I tried converting python2 code to python3 using 2to3 tool. It changed:
../wizard/product_configurator.py line 137
dynamic_fields.values())
to
list(dynamic_fields.values()))
However, in your code you are still using "dynamic_fields.values())". Any specific reason for that?

**Comment by CGenie** [comment]
4. Is fixed.
As for 1. and 2 (3 is missing?) I think I reproduce the same behavior on v10 and I think it's an issue with configurator itself, not with migration to odoo v11.

**Comment by ska-ibees** [comment]
Thanks for the prompt actions and reply.

**Comment by GSLabIt** [comment]
Hi there, any ETA for this one?

**Comment by CGenie** [comment]
@joezsweet Well we're testing this and fixing any issues that come up, can't quite estimate this but for us it looks stable and we already use it for one of the customers.
I guess tests should be fixed as well.

**Comment by Danoolo** [comment]
Hi everyone!..i want to ask you about website_configurator...with this module functionality about 'Reset' button and others elements with js controllers don't work so that it produces that website configurator is incomplete because others python logic functions and controllers are good and e.g. in 'config_ok' button in the product_template form view the traslation doesn't work either. My question is, in your versions does these functions work properly?. Thanks in advance

**Comment by Danoolo** [comment]
Hi guys!..commit 2602a24 fixes problem with onchange methods in form view like you said CGenie, thanks a lot, but configuration button (id='submit_configuration') doesn't send the request for variant creation..and in your last commit https://github.com/pledra/odoo-product-configurator/pull/152/commits/042a26aa0e8f5ee95e0a58ed4b8334d88d016169 ...in my version, the selected fields doesn't let me to pick any option. Thank you for your collab CGenie!

**Comment by Danoolo** [comment]
> Hi guys!..commit [2602a24](https://github.com/pledra/odoo-product-configurator/commit/2602a24343a1e3d2b8a49620bd74e2d983b97aa7) fixes problem with onchange methods in form view like you said CGenie, thanks a lot, but configuration button (id='submit_configuration') doesn't send the request for variant creation..and in your last commit [042a26a](https://github.com/pledra/odoo-product-configurator/commit/042a26aa0e8f5ee95e0a58ed4b8334d88d016169) ...in my version, the selected fields doesn't let me to pick any option. Thank you for your collab CGenie!

I was studying that problem, and i watch that post method doesn't have any item so in controller method cfg_session it checks about if post variable has elements, so it doesn't return anything. This post variable required of an 'add_qty' number referring to quantity of variant to order.

**Comment by CGenie** [comment]
@Danoolo For me this seems to work... I mean I do have the variants created.

**Comment by Danoolo** [comment]
@CGenie thks a lot for interesting...
captura de pantalla de 2018-10-12 16-10-13
That's the first problem i mentioned..in wrench icon always figure that traslation "In", i supposed it's the standard traslation..
Other problem i have with website configurator i can to solve..but i had to add an element in post variable..i'm not sure if it's a problem with my browser or i dont know...
Again thks a lot.

**Comment by Danoolo** [comment]
I have installed spanish-AR language..can this language making that issue?

**Comment by GSLabIt** [comment]
Is this ready to be merged in 11.0?

**Comment by CGenie** [comment]
Well we work with this module for some time now and it seems to work fine.
There is no v11.0 anyways, I guess it's good to merge it and fix bugs when they are reported. :)

**Comment by CGenie** [comment]
I guess the tests could be fixed, that is one thing that bothers me :)

**Comment by SalahAdDin** [comment]
@CGenie did you test the `product-variant` repository in OCA modules?

**Comment by bennals** [comment]
I just tried this module and struck the following error when clicking on the 'Add to Cart' button.  Nothing happens in the browser - just this error in the log.

Traceback (most recent call last):
  File "/home/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-server/addons/website_sale_options/controllers/main.py", line 70, in modal
    product = request.env['product.product'].with_context(product_context).browse(int(product_id))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Is the Website configurator working properly for others?   FYI, the 'Add to Cart' button works fine for webstore purchases of products that are not 'Configurable Templates'.

**Comment by Danoolo** [comment]
@bennals For me works fine!...but in website_product_configurator you do not have to add it to the cart, you only have to configure the variant and then it add to cart inmediatly...

**Comment by bennals** [comment]
@Danoolo thanks for replying.  Well that automatic adding to cart after configuration is not happening here either.

I found a similar issue reported on Pledra's repositry [here](https://github.com/pledra/odoo-product-configurator/issues/137)

Any ideas about the error?

**Comment by Danoolo** [comment]
@bennals Excuse me i got it...well that error says that product with 'product_id' has a None type value, try to follow the controller.py file...above in this chatter i mentioned an error similar when a configure in website and i had to manually add a value for the dict key 'add_qty'.. https://github.com/pledra/odoo-product-configurator/pull/152#issuecomment-428283138 ...maybe it's not the solution for your problem and i dont remember the error dialogue i got..

**Pull request closed without merging**
