### PR TITLE
[MIG] product_configurator, product_configurator_mrp, product_configurator_wizard -> v11

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
Hi all,

We (ERP|OPEN) started a migration to version 11. I can confirm the happy flow of using the configurator and getting a BoM attached to the product is working.

Any feedback is welcome.

We only worked on:

- product_configurator
- product_configurator_mrp
- product_configurator_wizard

### CODE REVIEW

**Comment by buzzy3** [comment]
Could i test it ? uname @mac.com

**Comment by lukebranch** [comment]
@PCatinean ,

Would it be possible to create an 11.0 branch for this repo (even if there are unported modules in the repo with Installable = False)? We have some prospects interested in the configurator for 11.0, and it would be useful to be able to target PR's to the official 11.0 branch (eg. such as @CasVissers PR here).

**Comment by PCatinean** [comment]
@lukebranch I will try to create an empty branch soon with a README file of changes/updates and fixes done so far + roadmap.

I've been working on the migration for a bit now and it seems I'm close to having the basic functionalities working with V11 in the refactored version.

**Comment by lukebranch** [comment]
@PCatinean ,

That's excellent news. Thanks for the update!

**Comment by BT-astauder** [comment]
@CasVissers I had to fix an import for 11.0. But as far as I can see, then it works quite nice:
https://github.com/brain-tec/odoo-product-configurator/commit/00fc32e732dd53fa01145c3af808d44dacf494fb

The only "bug" I have right now, is that the reconfiguration of a product in a sale.order.line does not load the old configuration. But I don't know if this was ever thought to work as I expect.

**Comment by CasVissers-360ERP** [comment]
See #152

**Pull request closed without merging**
